### PR TITLE
Create es.po

### PR DESCRIPTION
**Pull request by Sher852**
Added Spanish translation

### CODE REVIEW

**Review by Arc676 — CHANGES_REQUESTED** [review]
Add copyright line to top of file with name of contributor, per GPL3 guidelines, plus email for consistency.

**Comment by Arc676** [comment]
Thank you for your interest in the project and contributions!

**Comment by Arc676** [comment]
I meant at the very top of the file. Right after line 2.
```
Copyright (C) 2018 (your name or pseudonym) (your email)
```

**Comment by Sher852** [comment]
Done! 
Sorry if I didn't understand you properly. :)

**Review by Arc676 — APPROVED** [review]

**Pull request merged**
